### ISSUE TITLE
[Request] Check if any random query parameters are reflected in the response 

### ISSUE THREAD

**Issue by bugbaba** [Sh1Yo/x8#17]
Привет Hope you are doing well.

For use cases where all URL query is reflected back in the response, Like in below php code which dumps all the query parameters.

```php
<?php

  echo "Test";
  print_r($_GET);

?>
```

Currently this isn't getting detected. I was expecting it to show that all parameters in the wordlist are reflecting back, But the output was empty. To check for these a random **unusual**  parameter should be sent and check if it gets reflected back (may be stop further probes in that case).

![image](https://user-images.githubusercontent.com/29960776/156875021-31319df0-a9ef-4736-b6f8-2e330a661c8b.png)

--
Regards,
@bugbaba

**Comment by Sh1Yo** [comment]
Hi. The tool can perfectly detect such cases.
For example it would be able to find parameters in the following code:
 ```php
<?php
  echo "Test";
  print_r($_GET);
 
  echo $_GET["parameter"];
?>
```

When the tool prints `reflected` it doesn't indicate whether the parameter was reflected or not. It says that the parameter was reflected the different amount of times.

That's why there is a `Reflections` field in the initialization message. It tells how many times every parameter usually reflects on the page.
